import { Open_Sans } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

import { AppContext } from "@/components/aptosIntegrations/AppContext";
import { ReduxAppProvider } from "@/redux/provider";
import {
  queryClient,
  QueryClientProvider,
} from "@/components/common/react_query";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
const sans = Open_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "PetZ Money",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={sans.className}>
        <QueryClientProvider client={queryClient}>
          <ReduxAppProvider>
            <Navbar />
            <AppContext>
              <Toaster position="top-center " />

              {children}
            </AppContext>
            <Footer />
          </ReduxAppProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
