import { Open_Sans } from "next/font/google";
import "./globals.css";
import { AppContext } from "@/components/aptosIntegrations/AppContext";
import {
  queryClient,
  QueryClientProvider,
} from "@/components/common/react_query";
const sans = Open_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "PetZ Money",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={sans.className}>
        <QueryClientProvider client={queryClient}>
          <AppContext>{children}</AppContext>
        </QueryClientProvider>
      </body>
    </html>
  );
}
